import { collapse, Filter } from './collapse'

const filters: Record<string, Filter> = {
    plural: (_: string) => _ + 's',
    capitalise: ([first, ...rest]: string) => {
        if (!first) return ''
        return first.toLocaleUpperCase() + rest.join('')
    },
}

const rules = {
    title: [
        'buddy',
        'pal',
        'girl',
        'bestie',
        'gal',
        'soul sister',
        'sis',
        'chica',
        'missy',
        'homegirl',
        'king',
        'champ',
        'bro',
        'amigo',
        'bubba',
        'tiny',
        'sport',
        'slim',
        'chief',
        'buck',
        'coach',
        'dude',
        'buster',
        'bud',
        'boo',
        'mouse',
        'munchkin',
        'bee',
        'dolly',
        'precious',
        'bug',
        'chipmunk',
        'dottie',
        'cutie pie',
        'sweetums',
        'nugget',
        'kiddo',
        'smarty',
        'ace',
        'my lovely tadpole',
        'my fellow frog',
        'my fellow amphibian',
    ],

    intro: [
        'Fact,',
        'Oi!',
        'Oi #title#!',
        'Everybody agrees:',
        'Daaamp #title#,',
        'Check this out:',
        'Just saying',
        'News flash:',
        "I'm 100% sure",
        "I'm positive that",
        'My amphibian brain tells me',
        'If you wanna know what I think',
        'Hear me,',
        'Hear me #title#,',
        'Listen up, #title#,',
        'Okay, listen up:',
        'Okay, listen up #title#:',
    ],

    what: [
        'everything you do',
        'everything about you',
        'your mere existence',
        'your effortless cool',
        'your style',
        'your mind',
        'your endless talent',
        'the way you dance',
        'your presence',
        'your every idea',
        'everything about you',
        'the way you roll',
        'who you are',
    ],

    bodyPart: ['heart', 'soul', 'gills'],
    bodyPartAction: ['dance', 'shiver'],

    compliment: [
        'is raw horsepower',
        'is better than chocolate',
        'is a miracle',
        'lights the room on fire',
        'makes my #bodyPart# #bodyPartAction#',
        'is everything',
        'has that Special Something(™)',
        'is all that and a bag of chips',
        'rocks my world',
        'sizzles',
        "is the cat's meow",
        "is the bees' knees",
        "blows my froggin' mind",
        'rocks my socks',
        'tickles my gills',
        'floats my goat',
        'is solid gold',
        'is magic',
        'breeds miracles',
    ],
    suffix: [
        'Periodt!!1',
        'Periodt',
        "And I'm here for it!",
        'True story',
        "Y'know?",
        'you delicious beast',
        'Would I lie?',

        "and that's a fact.",
        'all night long.',
        'high five ✋🏻🐸!',
        '<ribbit!>',
        "and frogs don't lie.",
        "and that's a tadpole fact",
        "and that's a froggy fact",
        'You get me?',
        'You grok?',
    ],

    thingsYouDo: ['sing', 'walk', 'chirp', 'roll'],
    thingYouAre: [
        'soul',
        'heart',
        'touch',
        'interesting (yet pleasant) smell',
        'hair today',
        'style',
        'smell',
        'kindness',
        'tadpole',
        'chirp',
        'spirit',
        'vibe',
    ],

    reactionVerb: ['love', 'adore', 'worship', 'dig'],
    thingsYouHave: ['gills', 'eyes', 'ears'],

    templated: [
        '#intro# I #reactionVerb# your #thingsYouHave#',
        'I #reactionVerb# your #thingsYouHave#',
        '#intro# the way you #thingsYouDo# #compliment#. #suffix#',
        '#intro# your #thingYouAre# #compliment#. #suffix#',
        '#intro# #what# #compliment#. #suffix.capitalise#',
        '#intro# #what# #compliment#',
        'I #reactionVerb# your #thingYouAre#',
    ],

    blessing: ['#templated#'],
}

export const getRandomBlessing = () => collapse(rules, '#blessing#', filters)
